# This file generates the GitHub Actions matrix.
#
# For simple board + shield combinations, add them to the top level board and
# shield arrays, 
# for more control, add individual board + shield combinations
# to the `include` property.
#
# You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
#
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#     artifact-name: corne_left_with_logging
#
---
include:
  # Dactyl 50
  - board: nice_nano_v2
    shield: hillside_d50_left nice_view
    # Uncomment these two lines to enable ZMK Studio support
    # snippet: studio-rpc-usb-uart
    # cmake-args: -DCONFIG_ZMK_STUDIO=y

  # Right side of Dactyl 50
  # After your initial builds,
  # you often can comment out these lines to reduce your build CPU use in half.
  # Keymap only changes only need t rebuild the central (left) side
  # as it manages the keymap.
  - board: nice_nano_v2
    shield: hillside_d50_right nice_view

  # Settings Reset board
  # You only need this when you are reshuffling MCU pairs around
  # Enable if needed
  # - board: nice_nano_v2
  #   shield: settings_reset
